---
name: "Build Containers Enterprise"

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build-containers-common:
    runs-on: ubuntu-latest
    outputs:
      containerver: ${{ steps.getcontainerver.outputs.containerver }}
    steps:
      - name: Get Container Version
        id: getcontainerver
        run: |
          echo "containerver=$(date +'%s')" >> "$GITHUB_OUTPUT"

  build-containers:
    needs: build-containers-common
    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            release_suffix: ubuntu
            arch: amd64
        platform: [linux/amd64]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # submodules: 'true'
          token: ${{ secrets.PAT_TOKEN }}

      - name: Login to docker.io
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: docker build
        run: ./var/docker/docker-build.sh

      - name: Print post-build debug info
        run: |
          docker images

      - name: docker tag
        env: 
          CONTAINERVER: ${{ needs.build-containers-common.outputs.containerver }}
        run: |
          docker tag localhost/thinkthankmedia feelguuds/thinkthankmedia-enterprise:${{ matrix.arch }}-${{ env.CONTAINERVER }}
          docker push feelguuds/thinkthankmedia-enterprise:${{ matrix.arch }}-${{ env.CONTAINERVER }}

          docker tag localhost/thinkthankmedia-devcontainer feelguuds/thinkthankmedia-devcontainer-enterprise:${{ env.CONTAINERVER }}
          docker push feelguuds/thinkthankmedia-devcontainer-enterprise:${{ env.CONTAINERVER }}

          docker tag feelguuds/thinkthankmedia-devcontainer-enterprise:${{ env.CONTAINERVER }} feelguuds/thinkthankmedia-devcontainer-enterprise:latest
          docker push feelguuds/thinkthankmedia-devcontainer-enterprise:latest

  build-container-manifest:
    needs: [build-containers, build-containers-common]
    runs-on: ubuntu-latest
    steps:
      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create Docker Manifest 
        env: 
          CONTAINERVER: ${{ needs.build-containers-common.outputs.containerver }}
        run: |
          docker manifest create \
            feelguuds/thinkthankmedia-enterprise:latest \
            feelguuds/thinkthankmedia-enterprise:${{ env.CONTAINERVER }} \
            feelguuds/thinkthankmedia-enterprise:${{ env.CONTAINERVER }}

          docker manifest push feelguuds/thinkthankmedia-enterprise:latest
